// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package recovery

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :execresult
INSERT INTO recoveries (id, user_id) VALUES (?, ?)
`

type CreateParams struct {
	ID     string
	UserID int32
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, create, arg.ID, arg.UserID)
}

const deleteByID = `-- name: DeleteByID :execresult
DELETE FROM recoveries WHERE id = ?
`

func (q *Queries) DeleteByID(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteByID, id)
}

const readByID = `-- name: ReadByID :one
SELECT id, user_id, created_at FROM recoveries WHERE id = ? LIMIT 1
`

func (q *Queries) ReadByID(ctx context.Context, id string) (Recovery, error) {
	row := q.db.QueryRowContext(ctx, readByID, id)
	var i Recovery
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const readByUserID = `-- name: ReadByUserID :many
SELECT id, user_id, created_at FROM recoveries where user_id = ?
`

func (q *Queries) ReadByUserID(ctx context.Context, userID int32) ([]Recovery, error) {
	rows, err := q.db.QueryContext(ctx, readByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recovery
	for rows.Next() {
		var i Recovery
		if err := rows.Scan(&i.ID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
