// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package users

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO
    users (
        email,
        username,
        password,
        role
    )
VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Email    string
	Username string
	Password string
	Role     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Role,
	)
}

const readUserByEmail = `-- name: ReadUserByEmail :one
SELECT
    id,
    email,
    username,
    password,
    role
FROM users
WHERE
    email = ?
LIMIT 1
`

func (q *Queries) ReadUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const readUserByID = `-- name: ReadUserByID :one
SELECT
    id,
    email,
    username,
    password,
    role
FROM users
WHERE
    id = ?
LIMIT 1
`

func (q *Queries) ReadUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const readUserByUsername = `-- name: ReadUserByUsername :one
SELECT
    id,
    email,
    username,
    password,
    role
FROM users
WHERE
    username = ?
LIMIT 1
`

func (q *Queries) ReadUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, readUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
	)
	return i, err
}
