CREATE TABLE IF NOT EXISTS kalan (
    id int PRIMARY KEY AUTO_INCREMENT,
    entry VARCHAR(255) NOT NULL,
    pos VARCHAR(255) NOT NULL,
    gloss VARCHAR(255) NOT NULL,
    notes VARCHAR(255) NOT NULL
);