CREATE TABLE IF NOT EXISTS recoveries (
    id varchar(255) PRIMARY KEY NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);