name: Deploy Build
on:
  push:

jobs:
  Verify:
    uses: ./.github/workflows/verify.yml
  
  Publish:
    needs: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6
        
      - name: Build Binary
        run: |
          go mod tidy
          make

      - name: List paths
        run: |
          ls -a
          ls ./trg -a

      - name: Put Binary in Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SECRET_KEY }}
          source: "./trg/main"
          target: "/usr/local/bin/wilin/"