name: Verify Build and Tests
on:
  push:
    branches:
      - '**'
      - '!release'
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Build Binary
        run: |
          go mod tidy
          make
  
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Test Code
        run: |
          go mod tidy
          make test
