name: Demo Github Action
on:
  push:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Build Binary
        run: |
          go mod tidy
          go build -o ./trg/main .
  
  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4

      - name: Build Binary
        run: |
          go mod tidy
          go test ./...
