// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package proposal

import (
	"database/sql"
)

type Proposal struct {
	ID     int32
	UserID sql.NullInt32
	Entry  string
	Pos    string
	Gloss  string
	Notes  string
}

type User struct {
	ID       int32
	Email    string
	Username string
	Password string
	Role     string
}
