// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package proposal

import (
	"context"
	"database/sql"
)

const createProposal = `-- name: CreateProposal :execresult
INSERT INTO
    proposals (
        user_id,
        entry,
        pos,
        gloss,
        notes
    )
VALUES (?, ?, ?, ?, ?)
`

type CreateProposalParams struct {
	UserID sql.NullInt32
	Entry  string
	Pos    string
	Gloss  string
	Notes  string
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProposal,
		arg.UserID,
		arg.Entry,
		arg.Pos,
		arg.Gloss,
		arg.Notes,
	)
}

const readAllProposalsWithUsername = `-- name: ReadAllProposalsWithUsername :many
SELECT p.id, p.user_id, u.username, p.entry, p.pos, p.gloss, p.notes
FROM proposals p
    JOIN users u ON u.id = p.user_id
`

type ReadAllProposalsWithUsernameRow struct {
	ID       int32
	UserID   sql.NullInt32
	Username string
	Entry    string
	Pos      string
	Gloss    string
	Notes    string
}

func (q *Queries) ReadAllProposalsWithUsername(ctx context.Context) ([]ReadAllProposalsWithUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, readAllProposalsWithUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadAllProposalsWithUsernameRow
	for rows.Next() {
		var i ReadAllProposalsWithUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Entry,
			&i.Pos,
			&i.Gloss,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readProposalByIDWithUsername = `-- name: ReadProposalByIDWithUsername :one
SELECT p.id, p.user_id, u.username, p.entry, p.pos, p.gloss, p.notes
FROM proposals p
    JOIN users u ON u.id = p.user_id
WHERE
    p.id = ?
LIMIT 1
`

type ReadProposalByIDWithUsernameRow struct {
	ID       int32
	UserID   sql.NullInt32
	Username string
	Entry    string
	Pos      string
	Gloss    string
	Notes    string
}

func (q *Queries) ReadProposalByIDWithUsername(ctx context.Context, id int32) (ReadProposalByIDWithUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, readProposalByIDWithUsername, id)
	var i ReadProposalByIDWithUsernameRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.Entry,
		&i.Pos,
		&i.Gloss,
		&i.Notes,
	)
	return i, err
}

const readProposalsByUserIDWithUsername = `-- name: ReadProposalsByUserIDWithUsername :many
SELECT p.id, p.user_id, u.username, p.entry, p.pos, p.gloss, p.notes
FROM proposals p
    JOIN users u ON u.id = p.user_id
WHERE
    u.id = ?
`

type ReadProposalsByUserIDWithUsernameRow struct {
	ID       int32
	UserID   sql.NullInt32
	Username string
	Entry    string
	Pos      string
	Gloss    string
	Notes    string
}

func (q *Queries) ReadProposalsByUserIDWithUsername(ctx context.Context, id int32) ([]ReadProposalsByUserIDWithUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, readProposalsByUserIDWithUsername, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadProposalsByUserIDWithUsernameRow
	for rows.Next() {
		var i ReadProposalsByUserIDWithUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.Entry,
			&i.Pos,
			&i.Gloss,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
